import "./globals.css"
import type { Metadata } from "next"

const roboto = { className: "font-roboto" }

export const metadata: Metadata = {
  title: "Molly Specialty Sweets",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Marck+Script&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="../../static/pastry (1).png" sizes="32x32" />
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
